[project]
name = "data-engineering-progects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sadeq", email = "74061994+Sadeq-crypto@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
]

[project.scripts]
data-engineering-progects = "data_engineering_progects:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
